import { Controller, Inject } from '@sker/core'
import * as sdk from '@sker/sdk'
import { EventHourlyStatisticsService } from '@sker/entities'
import { logger } from '@sker/core'

@Controller(sdk.EventStatisticsController)
export class EventStatisticsController implements sdk.EventStatisticsController {
  constructor(
    @Inject(EventHourlyStatisticsService) private statisticsService: EventHourlyStatisticsService
  ) {}

  async triggerHourlyGeneration(
    body: sdk.TriggerGenerationRequest
  ): Promise<{ success: boolean; message: string }> {
    try {
      const snapshotTime = body.snapshotTime ? new Date(body.snapshotTime) : new Date()

      logger.info(`Manual hourly statistics generation requested at ${snapshotTime.toISOString()}`)

      return {
        success: true,
        message: 'Hourly statistics are auto-generated by subscribers. No manual action needed.',
      }
    } catch (error) {
      logger.error('Failed to trigger hourly generation:', error)
      return {
        success: false,
        message: error instanceof Error ? error.message : 'Unknown error',
      }
    }
  }

  async triggerDailyGeneration(
    body: sdk.TriggerGenerationRequest
  ): Promise<{ success: boolean; message: string }> {
    try {
      logger.info('Manual daily statistics generation requested')

      return {
        success: true,
        message: 'Daily statistics are aggregated from hourly data on demand. Use query API with granularity=daily.',
      }
    } catch (error) {
      logger.error('Failed to trigger daily generation:', error)
      return {
        success: false,
        message: error instanceof Error ? error.message : 'Unknown error',
      }
    }
  }

  async backfillHistoricalData(
    body: sdk.BackfillRequest
  ): Promise<{ success: boolean; message: string }> {
    try {
      const { eventId, startDate, endDate } = body

      logger.info(
        `Historical data backfill requested for event ${eventId} from ${startDate} to ${endDate}`
      )

      return {
        success: false,
        message: 'Backfill is deprecated. Hourly statistics are auto-generated by subscribers when new data arrives.',
      }
    } catch (error) {
      logger.error('Failed to process backfill request:', error)
      return {
        success: false,
        message: error instanceof Error ? error.message : 'Unknown error',
      }
    }
  }

  async queryStatistics(
    eventId: string,
    granularity: 'hourly' | 'daily' | 'weekly' | 'monthly',
    startTime: string,
    endTime: string
  ): Promise<sdk.StatisticsResult[]> {
    try {
      const results = await this.statisticsService.queryStatistics(
        eventId,
        granularity,
        new Date(startTime),
        new Date(endTime)
      )

      return results.map(r => ({ ...r, granularity }))
    } catch (error) {
      logger.error('Failed to query statistics:', error)
      throw error
    }
  }
}
