import { vi } from 'vitest';

export const createMockClient = () => ({
  options: {},
  get: vi.fn(),
  set: vi.fn(),
  setex: vi.fn(),
  setnx: vi.fn(),
  del: vi.fn(),
  exists: vi.fn(),
  quit: vi.fn().mockResolvedValue(undefined),
  zadd: vi.fn(),
  zincrby: vi.fn(),
  zscore: vi.fn(),
  zrangebyscore: vi.fn(),
  zremrangebyscore: vi.fn(),
  zrange: vi.fn(),
  zrevrange: vi.fn(),
  zcard: vi.fn(),
  zpopmax: vi.fn(),
  zrem: vi.fn(),
  hmset: vi.fn(),
  hset: vi.fn(),
  hget: vi.fn(),
  hgetall: vi.fn(),
  hdel: vi.fn(),
  expire: vi.fn(),
  ttl: vi.fn(),
  sadd: vi.fn(),
  sismember: vi.fn(),
  srem: vi.fn(),
  scard: vi.fn(),
  smembers: vi.fn(),
  lpush: vi.fn(),
  lrange: vi.fn(),
  ltrim: vi.fn(),
  keys: vi.fn(),
  pipeline: vi.fn(),
  publish: vi.fn(),
  subscribe: vi.fn(),
  on: vi.fn(),
  unsubscribe: vi.fn().mockResolvedValue(undefined),
});

export const createMockPipeline = () => ({
  get: vi.fn(),
  set: vi.fn(),
  setex: vi.fn(),
  del: vi.fn(),
  zincrby: vi.fn(),
  zadd: vi.fn(),
  expire: vi.fn(),
  hmset: vi.fn(),
  hset: vi.fn(),
  exec: vi.fn(),
});
