// 导入即自动注册（通过 @Injectable 装饰器）
import './WeiboLoginBrowserVisitor';
import './WeiboKeywordSearchBrowserVisitor';
import './WeiboAjaxStatusesShowBrowserVisitor';
import './WeiboAjaxStatusesCommentBrowserVisitor';
import './WeiboAjaxStatusesRepostTimelineBrowserVisitor';
import './WeiboAjaxStatusesLikeShowBrowserVisitor';
import './WeiboAjaxStatusesMymblogBrowserVisitor';
import './WeiboAjaxProfileInfoBrowserVisitor';
import './WeiboAjaxFriendshipsBrowserVisitor';
import './WeiboAjaxFeedHotTimelineBrowserVisitor';
import './PostContextCollectorBrowserVisitor';
import './PostNLPAnalyzerBrowserVisitor';
import './EventAutoCreatorBrowserVisitor';
import './WorkflowGraphBrowserVisitor';
import "./WeiboUserDetectionAstVisitor";
import "./LlmTextAgentAstVisitor";
import "./WeiboAccountPickAstBrowserVisitor"
import "./CollectorVisitor";
import "./ImageBrowserVisitor";
import "./VideoBrowserVisitor";
import "./AudioBrowserVisitor";
import "./TextAreaAstVisitor";
import "./IfAstVisitor";
import "./ShareAstVisitor";
import "./DateAstVisitor";
import "./StoreVisitor";
import "./MqVisitor";
import "./LlmStructuredOutputAstVisitor";