import type { WeiboUserCategoryEntity } from '../weibo-user-category.entity';

type CategorySeed = Omit<
  WeiboUserCategoryEntity,
  'id' | 'created_at' | 'updated_at' | 'deleted_at'
>;

export const weiboUserCategoriesSeeds: CategorySeed[] = [
  {
    code: 'ordinary',
    name: '普通用户',
    name_en: 'Ordinary User',
    dimension: 'verification',
    description: '未经过认证的普通用户',
    icon: 'user',
    color: '#999999',
    sort: 100,
    status: 'active',
  },
  {
    code: 'personal_verified',
    name: '个人认证',
    name_en: 'Personal Verified',
    dimension: 'verification',
    description: '个人实名认证用户（黄V）',
    icon: 'user-check',
    color: '#F59E0B',
    sort: 90,
    status: 'active',
  },
  {
    code: 'org_verified',
    name: '机构认证',
    name_en: 'Organization Verified',
    dimension: 'verification',
    description: '企业或组织认证账号（蓝V）',
    icon: 'building',
    color: '#3B82F6',
    sort: 80,
    status: 'active',
  },
  {
    code: 'institution_verified',
    name: '政务认证',
    name_en: 'Institution Verified',
    dimension: 'verification',
    description: '政府机构或事业单位认证',
    icon: 'landmark',
    color: '#EF4444',
    sort: 70,
    status: 'active',
  },
  {
    code: 'other_verified',
    name: '其他认证',
    name_en: 'Other Verified',
    dimension: 'verification',
    description: '其他类型的认证账号',
    icon: 'shield-check',
    color: '#8B5CF6',
    sort: 110,
    status: 'active',
  },

  {
    code: 'top_influencer',
    name: '头部KOL',
    name_en: 'Top Influencer',
    dimension: 'influence',
    description: '粉丝数 ≥ 100万的顶级影响力账号',
    icon: 'crown',
    color: '#DC2626',
    sort: 10,
    status: 'active',
  },
  {
    code: 'major_influencer',
    name: '头部达人',
    name_en: 'Major Influencer',
    dimension: 'influence',
    description: '粉丝数 10万-100万的主流影响力账号',
    icon: 'star',
    color: '#F59E0B',
    sort: 20,
    status: 'active',
  },
  {
    code: 'mid_influencer',
    name: '腰部达人',
    name_en: 'Mid-tier Influencer',
    dimension: 'influence',
    description: '粉丝数 1万-10万的中等影响力账号',
    icon: 'trending-up',
    color: '#10B981',
    sort: 30,
    status: 'active',
  },
  {
    code: 'micro_influencer',
    name: '尾部达人',
    name_en: 'Micro Influencer',
    dimension: 'influence',
    description: '粉丝数 1千-1万的小影响力账号',
    icon: 'users',
    color: '#6366F1',
    sort: 40,
    status: 'active',
  },
  {
    code: 'tail_user',
    name: '长尾用户',
    name_en: 'Tail User',
    dimension: 'influence',
    description: '粉丝数 < 1千的普通用户',
    icon: 'user-circle',
    color: '#94A3B8',
    sort: 50,
    status: 'active',
  },

  {
    code: 'brand_account',
    name: '品牌账号',
    name_en: 'Brand Account',
    dimension: 'capability',
    description: '具有品牌营销能力的账号',
    icon: 'award',
    color: '#EC4899',
    sort: 60,
    status: 'active',
  },
  {
    code: 'ecommerce_account',
    name: '电商账号',
    name_en: 'E-commerce Account',
    dimension: 'capability',
    description: '具有电商销售能力的账号',
    icon: 'shopping-cart',
    color: '#F97316',
    sort: 61,
    status: 'active',
  },
  {
    code: 'live_streamer',
    name: '直播达人',
    name_en: 'Live Streamer',
    dimension: 'capability',
    description: '具有直播能力的账号',
    icon: 'video',
    color: '#EF4444',
    sort: 62,
    status: 'active',
  },
  {
    code: 'video_creator',
    name: '视频创作者',
    name_en: 'Video Creator',
    dimension: 'capability',
    description: '专注于视频内容创作的账号',
    icon: 'film',
    color: '#8B5CF6',
    sort: 63,
    status: 'active',
  },
  {
    code: 'content_creator',
    name: '内容创作者',
    name_en: 'Content Creator',
    dimension: 'capability',
    description: '专注于付费内容或专栏的创作者',
    icon: 'pen-tool',
    color: '#06B6D4',
    sort: 64,
    status: 'active',
  },

  {
    code: 'media',
    name: '媒体',
    name_en: 'Media',
    dimension: 'industry',
    description: '传统媒体或新媒体账号',
    icon: 'newspaper',
    color: '#3B82F6',
    sort: 200,
    status: 'active',
  },
  {
    code: 'news',
    name: '新闻',
    name_en: 'News',
    dimension: 'industry',
    description: '新闻资讯类账号',
    icon: 'radio',
    color: '#2563EB',
    sort: 201,
    status: 'active',
  },
  {
    code: 'entertainment',
    name: '娱乐',
    name_en: 'Entertainment',
    dimension: 'industry',
    description: '娱乐、影视、音乐等行业账号',
    icon: 'music',
    color: '#EC4899',
    sort: 202,
    status: 'active',
  },
  {
    code: 'finance',
    name: '财经',
    name_en: 'Finance',
    dimension: 'industry',
    description: '财经金融行业账号',
    icon: 'dollar-sign',
    color: '#10B981',
    sort: 203,
    status: 'active',
  },
  {
    code: 'tech',
    name: '科技',
    name_en: 'Technology',
    dimension: 'industry',
    description: '科技互联网行业账号',
    icon: 'cpu',
    color: '#6366F1',
    sort: 204,
    status: 'active',
  },
  {
    code: 'sports',
    name: '体育',
    name_en: 'Sports',
    dimension: 'industry',
    description: '体育运动行业账号',
    icon: 'activity',
    color: '#F59E0B',
    sort: 205,
    status: 'active',
  },
  {
    code: 'education',
    name: '教育',
    name_en: 'Education',
    dimension: 'industry',
    description: '教育培训行业账号',
    icon: 'book-open',
    color: '#8B5CF6',
    sort: 206,
    status: 'active',
  },
  {
    code: 'healthcare',
    name: '医疗健康',
    name_en: 'Healthcare',
    dimension: 'industry',
    description: '医疗健康行业账号',
    icon: 'heart',
    color: '#EF4444',
    sort: 207,
    status: 'active',
  },
  {
    code: 'government',
    name: '政府公共服务',
    name_en: 'Government',
    dimension: 'industry',
    description: '政府机构和公共服务账号',
    icon: 'landmark',
    color: '#DC2626',
    sort: 208,
    status: 'active',
  },
  {
    code: 'corporate',
    name: '企业',
    name_en: 'Corporate',
    dimension: 'industry',
    description: '一般企业账号',
    icon: 'briefcase',
    color: '#64748B',
    sort: 209,
    status: 'active',
  },
];
