export default {
  entry: ['src/main.ts'],
  format: ['esm'],
  dts: false,
  sourcemap: true,
  clean: true,
  target: 'node20',
  outDir: 'dist',
  external: [
    '@sker/agent',
    '@sker/auth',
    '@sker/chat',
    '@sker/core',
    '@sker/entities',
    '@sker/mq',
    '@sker/llm-protocol',
    '@sker/redis',
    '@sker/sdk',
    '@sker/utils',
    '@sker/workflow',
    '@sker/workflow-ast',
    '@sker/workflow-compiler',
    '@sker/workflow-run',
    'pg',
    'typeorm',
    'better-auth',
    'socket.io',
    'node-cron',
    'busboy',
    'redis',
    '@redis/client',
    '@redis/client/lib/lua-script',
    'amqplib',
    'mongodb'
  ]
}
